member entity created
melanger/pa165-photography-club pull request #2
Opened 2017-10-24 20:14 UTC by DenisFigula

2017-10-25 17:14 UTC, DenisFigula commented
review please :)

2017-10-25 19:47 UTC, melanger commented
Should we include the linking fields (e.g. Equipment.owner and/or Member.equipments)?

2017-10-26 09:12 UTC, DenisFigula commented
List of equipment should be included, in my opinion. I will add it after equipment entity is available

2017-10-26 09:39 UTC, melanger requested changes

2017-10-26 09:39 UTC, melanger commented on pa165-photography-club-ejb/src/main/java/cz/muni/fi/pa165/photographyclub/Gender.java
> +    MALE, FEMALE, APACHE
Should we dig into something more than male and female?

2017-10-26 09:39 UTC, melanger commented on pa165-photography-club-ejb/src/main/java/cz/muni/fi/pa165/photographyclub/Member.java
> +    private BufferedImage photo;
I would probably stick with a String with the file name (later the URL) of the image.

2017-10-27 14:58 UTC, DenisFigula commented on pa165-photography-club-ejb/src/main/java/cz/muni/fi/pa165/photographyclub/Gender.java
> +    MALE, FEMALE, APACHE
updated

2017-10-27 17:53 UTC, melanger approved these changes

2017-10-27 17:54 UTC, merged